workflows:
  android-build:
    name: Android APK Build
    max_build_duration: 15
    environment:
      vars:
        PACKAGE_NAME: "com.budgetbuddy.app"
      node: 18
    scripts:
      - name: Install Dependencies
        script: |
          npm install
      - name: Build Web App
        script: |
          npm run build
      - name: Capacitor Sync
        script: |
          npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
